---
ceph_pv_name: "rbd"
ceph_pool: "kube"
ceph_provisioner_version: "v2.1.1-k8s1.11"

ceph_mon:
 - 127.0.0.1:6789

# ceph auth get-key client.admin | base64
ceph_admin_secret: "Y2VwaF9hZG1pbl9wYXNzCg=="

# ceph auth add client.kube mon 'allow r' osd 'allow rwx pool=kube'
# ceph auth get-key client.kube | base64
ceph_secret: "Y2VwaF9rdWJlX3Bhc3MK"

ceph_rbd_default_pv: false
ceph_force: false
